// SystemVerilog netlist generated by the Virtuoso SystemVerilog Netlister
// IC subversion:  IC23.1-64b.ISR13.25 
// Xcelium version: 23.09-s004
// Copyright(C) 2005-2009, Cadence Design Systems, Inc
// User: lieuwe Pid: 193991
// Design library name: LIB_PEPPER_NSADC
// Design cell name: ns_sar_v2
// Design view name: verilog_config

//systemVerilog HDL for "LIB_PEPPER_NSADC", "comparator_digital" "systemVerilog"


module comparator_digital ( DEBUG, OUT, READY, CLOCK, DGND, DVDD, VIN, VIP );

  input 
`ifdef XCELIUM
    (* integer supplySensitivity = "DVDD"; *)
`endif
  DGND;
  input real
`ifdef XCELIUM
    (* integer supplySensitivity = "DVDD";
       integer groundSensitivity = "DGND"; *)
`endif
  VIN;
  output logic
`ifdef XCELIUM
    (* integer supplySensitivity = "DVDD";
       integer groundSensitivity = "DGND"; *)
`endif
  OUT;
  input logic
`ifdef XCELIUM
    (* integer supplySensitivity = "DVDD";
       integer groundSensitivity = "DGND"; *)
`endif
  CLOCK;
  input 
`ifdef XCELIUM
    (* integer groundSensitivity = "DGND"; *)
`endif
  DVDD;
  output logic
`ifdef XCELIUM
    (* integer supplySensitivity = "DVDD";
       integer groundSensitivity = "DGND"; *)
`endif
  READY;
  output logic DEBUG;
  input real
`ifdef XCELIUM
    (* integer supplySensitivity = "DVDD";
       integer groundSensitivity = "DGND"; *)
`endif
  VIP;


	// INIT
	initial begin
		DEBUG <= 1'b0;
		OUT <= 1'b0;
	end

    // OUT updates at rising edge of CLOCK
    always_ff @(posedge CLOCK) begin
        if (VIP > VIN)
            OUT <= 1'b1;
        else
            OUT <= 1'b0;
		DEBUG <= !DEBUG;
    end

    // READY follows CLOCK but delayed by 5 ns
    assign #(20) READY = CLOCK;


endmodule


// Library - LIB_PEPPER_NSADC, Cell - sar_controller_10b_mes1, View -
//schematic
// LAST TIME SAVED: Oct 19 16:50:43 2025
// NETLIST TIME: Jan 24 09:35:45 2026

`include "/usr/local/cadence/kits/tsmc/180nm_BCD2/tsmc_libs/libs_r1a_2024/TSMCHOME/digital/Front_End/verilog/tcb018gbwp7t_270a/tcb018gbwp7t_edited.v"

module sar_controller_10b_mes1 ( DONE, DWA_DATA, 
    {DWA_ENABLE[3],DWA_ENABLE[2],DWA_ENABLE[1],DWA_ENABLE[0]}, 
    MES_DATA, 
    {MES_ENABLE[5],MES_ENABLE[4],MES_ENABLE[3],MES_ENABLE[2],MES_ENABLE[1],MES_ENABLE[0]}, 
    POINTER, RESULT, CLK, CMP, DGND, DVDD, DWA, MES, SAMPLE, nARST );

output  DONE;

input  CLK, CMP, DGND, DVDD, DWA, MES, SAMPLE, nARST;

output [3:0]  POINTER;
output [9:0]  RESULT;
output [3:0]  DWA_DATA;
output [0:3]  DWA_ENABLE;
output [5:0]  MES_DATA;
output [0:5]  MES_ENABLE;

interconnect MES;
interconnect nARST;
interconnect CMP;
interconnect CLK;
interconnect DVDD;
interconnect DGND;
interconnect clear_state_n;
interconnect sample_mes;
interconnect tie_low;
interconnect tie_high;
interconnect SAMPLE;
interconnect DWA;
interconnect DONE;
// Buses in the design

interconnect  [3:0]  POINTER;

interconnect  [9:0]  RESULT;

interconnect  [3:0]  DWA_DATA;

interconnect  [0:3]  DWA_ENABLE;

interconnect  [5:0]  MES_DATA;

interconnect  [0:5]  MES_ENABLE;

interconnect  [0:5]  net13;

interconnect  [0:3]  net7;

interconnect  [5:0]  data_s1_n;

interconnect  [3:0]  pointer_pre;

interconnect  [9:0]  data_carry;

interconnect  [0:5]  net3;

interconnect  [9:0]  data_s1;

interconnect  [10:1]  q_internal;

interconnect  [1:11]  sar_state;

interconnect  [3:0]  pointer_carry;

interconnect  [5:0]  data_s2;


HA1D2BWP7T  I27[3:0] ( .CO(data_carry[9:6]), .S(RESULT[9:6]), 
    .VDD(DVDD), .VSS(DGND), .A(data_s1[9:6]), .B(data_carry[8:5]));

AN2D4BWP7T  i_mes_ctrl ( .Z(sample_mes), .A2(MES), .VSS(DGND), 
    .VDD(DVDD), .A1(SAMPLE));

BUFFD2BWP7T  i_dwa_data[0:3] ( .Z(DWA_DATA[3:0]), .VDD(DVDD), 
    .VSS(DGND), .I(q_internal[10:7]));

BUFFD2BWP7T  i_enable_dwa[0:3] ( .Z(DWA_ENABLE[0:3]), .VDD(DVDD), 
    .VSS(DGND), .I({sar_state[4], sar_state[3], sar_state[2], 
    sar_state[1]}));

FA1D1BWP7T  I22[3:0] ( .CO(pointer_carry[3:0]), .S(pointer_pre[3:0]), 
    .VDD(DVDD), .VSS(DGND), .A(POINTER[3:0]), .B(net7[0:3]), 
    .CI({pointer_carry[2], pointer_carry[1], pointer_carry[0], 
    tie_low}));

AN2D0BWP7T  I20[3:0] ( .Z(net7[0:3]), .VDD(DVDD), .VSS(DGND), 
    .A1(q_internal[10:7]), .A2(DWA));

AN2D0BWP7T  I13[5:0] ( .Z(net13[0:5]), .VDD(DVDD), .VSS(DGND), 
    .A1(data_s2[5:0]), .A2(MES));

TIEHBWP7T  I0 ( .Z(tie_high), .VSS(DGND), .VDD(DVDD));

DFCNQD1BWP7T  I12[1:6] ( .Q(data_s2[5:0]), .VDD(DVDD), .VSS(DGND), 
    .CDN(nARST), .CP(DONE), .D(data_s1_n[5:0]));

DFCNQD1BWP7T  I11[1:10] ( .Q(data_s1[9:0]), .VDD(DVDD), .VSS(DGND), 
    .CDN(nARST), .CP(DONE), .D(q_internal[10:1]));

OR2D2BWP7T  i_mes_data[0:5] ( .Z(MES_DATA[5:0]), .VDD(DVDD), 
    .VSS(DGND), .A1(q_internal[6:1]), .A2(net3[0:5]));

OR2D2BWP7T  i_enable_mes[0:5] ( .Z(MES_ENABLE[0:5]), .VDD(DVDD), 
    .VSS(DGND), .A1({sar_state[10], sar_state[9], sar_state[8], 
    sar_state[7], sar_state[6], sar_state[5]}), .A2(sample_mes));

BUFFD4BWP7T  i_done ( .Z(DONE), .VSS(DGND), .VDD(DVDD), 
    .I(sar_state[11]));

TIELBWP7T  I2 ( .ZN(tie_low), .VSS(DGND), .VDD(DVDD));

DFCNQD2BWP7T  i_pointer_data[3:0] ( .Q(POINTER[3:0]), .VDD(DVDD), 
    .VSS(DGND), .CDN(nARST), .CP(SAMPLE), .D(pointer_pre[3:0]));

DFCNQD2BWP7T  i_sar_state[1:11] ( .Q(sar_state[1:11]), .VDD(DVDD), 
    .VSS(DGND), .CDN(clear_state_n), .CP(CLK), .D({tie_high, 
    sar_state[1], sar_state[2], sar_state[3], sar_state[4], 
    sar_state[5], sar_state[6], sar_state[7], sar_state[8], 
    sar_state[9], sar_state[10]}));

DFCNQD2BWP7T  i_sar_data[10:1] ( .Q(q_internal[10:1]), .VDD(DVDD), 
    .VSS(DGND), .CDN(clear_state_n), .CP(sar_state[1:10]), .D(CMP));

AN2D2BWP7T  mes_sample_data[0:5] ( .Z(net3[0:5]), .VDD(DVDD), 
    .VSS(DGND), .A1(data_s1[5:0]), .A2(sample_mes));

FA1D2BWP7T  I7[5:0] ( .CO(data_carry[5:0]), .S(RESULT[5:0]), 
    .VDD(DVDD), .VSS(DGND), .A(data_s1[5:0]), .B(net13[0:5]), 
    .CI({data_carry[4], data_carry[3], data_carry[2], data_carry[1], 
    data_carry[0], MES}));

INR2D4BWP7T  i_rst_fsm ( .ZN(clear_state_n), .B1(SAMPLE), .A1(nARST), 
    .VSS(DGND), .VDD(DVDD));

INVD1BWP7T  I28[5:0] ( .ZN(data_s1_n[5:0]), .VDD(DVDD), .VSS(DGND), 
    .I(data_s1[5:0]));

endmodule


// Library - LIB_PEPPER_NSADC, Cell - ns_sar_v2, View - schematic
// LAST TIME SAVED: Dec 13 10:45:53 2025
// NETLIST TIME: Jan 24 09:35:53 2026

`include "/usr/local/cadence/kits/tsmc/180nm_BCD2/tsmc_libs/libs_r1a_2024/TSMCHOME/digital/Front_End/verilog/tcb018gbwp7t_270a/tcb018gbwp7t_edited.v"

module ns_sar_v2 ( ANALOG_TEST, DIGITAL_DEBUG, DONE, OVERFLOW, RESULT, 
    ADC_SPARE, ANALOG_ENABLE, ANALOG_RESET_OVERRIDE, 
    ANALOG_RESET_OVERRIDE_VAL, ANALOG_TEST_SELECT, CHP_EN, DGND, 
    DIGITAL_DEBUG_SELECT, DONE_OVERRIDE, DONE_OVERRIDE_VAL, DVDD, 
    DWA_EN, EXT_CLK, EXT_CLK_EN, GAIN, IBIAS_500N_PTAT, MES_EN, OSR, 
    REFC, REFN, REFP, SAMPLE_CLK, VIN, VIP, nARST );

output  ANALOG_TEST, DIGITAL_DEBUG, DONE, OVERFLOW;

input  ANALOG_ENABLE, ANALOG_RESET_OVERRIDE, ANALOG_RESET_OVERRIDE_VAL, 
    CHP_EN, DGND, DONE_OVERRIDE, DONE_OVERRIDE_VAL, DVDD, DWA_EN, 
    EXT_CLK, EXT_CLK_EN, IBIAS_500N_PTAT, MES_EN, REFC, REFN, REFP, 
    SAMPLE_CLK, VIN, VIP, nARST;

output [15:0]  RESULT;

input [2:0]  ANALOG_TEST_SELECT;
input [7:0]  ADC_SPARE;
input [3:0]  OSR;
input [3:0]  GAIN;
input [2:0]  DIGITAL_DEBUG_SELECT;

interconnect ANALOG_TEST;
interconnect IBIAS_500N_PTAT;
interconnect DONE;
interconnect cic_done_pre;
interconnect ANALOG_ENABLE;
interconnect REFC;
interconnect VDACN;
interconnect VDACP;
interconnect DGND;
interconnect DVDD;
interconnect net10;
interconnect async_reset;
interconnect ctrl_reset_in;
interconnect DWA_EN;
interconnect CHP_EN;
interconnect SAMPLE_CLK;
interconnect nARST;
interconnect OVERFLOW;
interconnect ANALOG_RESET_OVERRIDE_VAL;
interconnect sample_internal;
interconnect MES_EN;
interconnect EXT_CLK_EN;
interconnect EXT_CLK;
interconnect REFN;
interconnect REFP;
interconnect VIN;
interconnect VIP;
interconnect sar_debug;
interconnect ANALOG_RESET_OVERRIDE;
interconnect digital_debug_pre1;
interconnect qnf_internal;
interconnect chopper_internal;
interconnect DONE_OVERRIDE;
interconnect sar_internal;
interconnect digital_debug_pre2;
interconnect DIGITAL_DEBUG;
interconnect DONE_OVERRIDE_VAL;
interconnect integrator_debug;
// Buses in the design

interconnect  [2:0]  ANALOG_TEST_SELECT;

interconnect  [7:0]  ADC_SPARE;

interconnect  [3:0]  OSR;

interconnect  [3:0]  GAIN;

interconnect  [2:0]  DIGITAL_DEBUG_SELECT;

interconnect  [15:0]  RESULT;

interconnect  [1:6]  data_mes;

interconnect  [1:6]  enable_mes;

interconnect  [14:0]  data_dwa;

interconnect  [1:0]  vx2n;

interconnect  [9:0]  sar_data;

interconnect  [14:0]  enable_dwa;

interconnect  [1:0]  vx1p;

interconnect  [1:0]  vx1n;

interconnect  [1:0]  vx2p;


sar_controller_top i_sar_controller ( .DEBUG(sar_debug), 
    .CHP_EN(CHP_EN), .DWA_EN(DWA_EN), .EXT_CLK(EXT_CLK), 
    .EXT_CLK_EN(EXT_CLK_EN), .MES_EN(MES_EN), 
    .CHOPPER_INTERNAL(chopper_internal), 
    .DWA_DATA_THERM(data_dwa[14:0]), 
    .DWA_ENABLE_THERM(enable_dwa[14:0]), .MES_DATA(data_mes[1:6]), 
    .MES_ENABLE(enable_mes[1:6]), .QNF_INTERNAL(qnf_internal), 
    .RESULT(sar_data[9:0]), .SAMPLE_INTERNAL(sample_internal), 
    .SAR_INTERNAL(sar_internal), .DGND(DGND), .DVDD(DVDD), 
    .SAMPLE_CLK(SAMPLE_CLK), .VDACN(VDACN), .VDACP(VDACP), 
    .nARST(nARST));

nssar_decimator_18b i_decimate ( .OVERFLOW(OVERFLOW), 
    .DECIMATOR_OUT(RESULT[15:0]), .INT_DEBUG(integrator_debug), 
    .DONE_OVERRIDE_VAL(DONE_OVERRIDE_VAL), 
    .DONE_OVERRIDE(DONE_OVERRIDE), .DGND(DGND), .DVDD(DVDD), 
    .CIC_DONE(cic_done_pre), .GAIN(GAIN[3:0]), .OSR(OSR[3:0]), 
    .SAMPLE_CLK(SAMPLE_CLK), .SAR_DATA(sar_data[9:0]), .nARST(nARST));

MUX2D2BWP7T  i_testmux_3 ( .Z(DIGITAL_DEBUG), .VSS(DGND), .VDD(DVDD), 
    .S(DIGITAL_DEBUG_SELECT[2]), .I1(digital_debug_pre2), 
    .I0(digital_debug_pre1));

MUX2D2BWP7T  i_ctrl_areset ( .Z(net10), .VSS(DGND), .VDD(DVDD), 
    .S(ANALOG_RESET_OVERRIDE), .I1(ANALOG_RESET_OVERRIDE_VAL), 
    .I0(cic_done_pre));

MUX4D2BWP7T  i_testmux_2 ( .Z(digital_debug_pre2), .VSS(DGND), 
    .VDD(DVDD), .S1(DIGITAL_DEBUG_SELECT[1]), 
    .S0(DIGITAL_DEBUG_SELECT[0]), .I3(sar_data[9]), .I2(cic_done_pre), 
    .I1(integrator_debug), .I0(sar_debug));

MUX4D2BWP7T  i_testmux_1 ( .S1(DIGITAL_DEBUG_SELECT[1]), 
    .S0(DIGITAL_DEBUG_SELECT[0]), .I3(chopper_internal), 
    .I2(qnf_internal), .Z(digital_debug_pre1), .VSS(DGND), .VDD(DVDD), 
    .I1(sar_internal), .I0(sample_internal));

BUFFD1BWP7T  I1 ( .I(cic_done_pre), .Z(DONE), .VSS(DGND), .VDD(DVDD));

OR2D1BWP7T  I11 ( .A2(net10), .A1(async_reset), .Z(ctrl_reset_in), 
    .VSS(DGND), .VDD(DVDD));

INVD1BWP7T  I12 ( .ZN(async_reset), .VSS(DGND), .VDD(DVDD), .I(nARST));

endmodule


// Library - LIB_PEPPER_NSADC, Cell - thermometer_encoder_2b, View -
//schematic
// LAST TIME SAVED: Oct 26 09:58:31 2025
// NETLIST TIME: Jan 24 09:35:47 2026

`include "/usr/local/cadence/kits/tsmc/180nm_BCD2/tsmc_libs/libs_r1a_2024/TSMCHOME/digital/Front_End/verilog/tcb018gbwp7t_270a/tcb018gbwp7t_edited.v"

module thermometer_encoder_2b ( THERM, BINARY, DGND, DVDD, 
    OVERRIDE_HIGH, OVERRIDE_LOW );


input  DGND, DVDD, OVERRIDE_HIGH, OVERRIDE_LOW;

output [3:0]  THERM;

input [1:0]  BINARY;

interconnect OVERRIDE_LOW;
interconnect DVDD;
interconnect DGND;
interconnect OVERRIDE_HIGH;
interconnect net2;
// Buses in the design

interconnect  [1:0]  BINARY;

interconnect  [3:0]  THERM;

interconnect  [2:0]  therm_pre_n;


NR2D2BWP7T  I8[2:0] ( .ZN(THERM[2:0]), .VDD(DVDD), .VSS(DGND), 
    .A1(therm_pre_n[2:0]), .A2(OVERRIDE_LOW));

AN2D1BWP7T  I1 ( .Z(net2), .VSS(DGND), .VDD(DVDD), .A2(BINARY[0]), 
    .A1(BINARY[1]));

NR3D1BWP7T  I2 ( .A3(OVERRIDE_HIGH), .ZN(therm_pre_n[0]), .VSS(DGND), 
    .VDD(DVDD), .A2(BINARY[0]), .A1(BINARY[1]));

NR2D1BWP7T  I10 ( .A2(OVERRIDE_HIGH), .A1(BINARY[1]), 
    .ZN(therm_pre_n[1]), .VSS(DGND), .VDD(DVDD));

NR2D1BWP7T  I11 ( .A2(OVERRIDE_HIGH), .A1(net2), .VDD(DVDD), 
    .ZN(therm_pre_n[2]), .VSS(DGND));

BUFFD2BWP7T  I9 ( .Z(THERM[3]), .VSS(DGND), .VDD(DVDD), 
    .I(OVERRIDE_HIGH));

endmodule


// Library - LIB_PEPPER_NSADC, Cell - sar_controller_top, View -
//schematic
// LAST TIME SAVED: Oct 26 09:58:46 2025
// NETLIST TIME: Jan 24 09:35:51 2026

`include "/usr/local/cadence/kits/tsmc/180nm_BCD2/tsmc_libs/libs_r1a_2024/TSMCHOME/digital/Front_End/verilog/tcb018gbwp7t_270a/tcb018gbwp7t_edited.v"

module sar_controller_top ( CHOPPER_INTERNAL, DEBUG, DWA_DATA_THERM, 
    DWA_ENABLE_THERM, MES_DATA, MES_ENABLE, QNF_INTERNAL, RESULT, 
    SAMPLE_INTERNAL, SAR_INTERNAL, CHP_EN, DGND, DVDD, DWA_EN, EXT_CLK, 
    EXT_CLK_EN, MES_EN, SAMPLE_CLK, VDACN, VDACP, nARST );

output  CHOPPER_INTERNAL, DEBUG, QNF_INTERNAL, SAMPLE_INTERNAL, 
    SAR_INTERNAL;

input  CHP_EN, DGND, DVDD, DWA_EN, EXT_CLK, EXT_CLK_EN, MES_EN, 
    SAMPLE_CLK, VDACN, VDACP, nARST;

output [14:0]  DWA_ENABLE_THERM;
output [14:0]  DWA_DATA_THERM;
output [5:0]  MES_DATA;
output [5:0]  MES_ENABLE;
output [9:0]  RESULT;

interconnect nARST;
interconnect SAMPLE_INTERNAL;
interconnect comparator_trigger_pre;
interconnect MES_EN;
interconnect SAR_INTERNAL;
interconnect DEBUG;
interconnect net15;
interconnect VDACP;
interconnect VDACN;
interconnect comparator_eval;
interconnect sar_done;
interconnect comparator_ready;
interconnect DVDD;
interconnect DGND;
interconnect comparator_trigger;
interconnect SAMPLE_CLK;
interconnect CHOPPER_INTERNAL;
interconnect QNF_INTERNAL;
interconnect net12;
interconnect net22;
interconnect net2;
interconnect comparator_dout;
interconnect EXT_CLK;
interconnect DWA_EN;
interconnect net7;
interconnect net10;
interconnect debug_pre;
interconnect net14;
interconnect EXT_CLK_EN;
interconnect sample_digital;
interconnect sample_clk_buff;
interconnect CHP_EN;
// Buses in the design

interconnect  [14:0]  DWA_ENABLE_THERM;

interconnect  [14:0]  DWA_DATA_THERM;

interconnect  [5:0]  MES_DATA;

interconnect  [5:0]  MES_ENABLE;

interconnect  [9:0]  RESULT;

interconnect  [3:0]  dwa_enable;

interconnect  [3:0]  pointer;

interconnect  [3:0]  dwa_data;

interconnect  [6:0]  comparator_delay;


sar_controller_10b_mes1 i_sar_control ( sar_done, dwa_data[3:0], 
    dwa_enable[3:0], MES_DATA[5:0], MES_ENABLE[5:0], pointer[3:0], 
    RESULT[9:0], comparator_ready, comparator_dout, DGND, DVDD, DWA_EN, 
    MES_EN, sample_digital, nARST);

comparator_digital i_comparator ( .DEBUG(debug_pre), 
    .OUT(comparator_dout), .READY(comparator_ready), 
    .CLOCK(comparator_eval), .DGND(DGND), .DVDD(DVDD), .VIN(VDACN), 
    .VIP(VDACP));

INVD2BWP7T  I4 ( .ZN(DEBUG), .VSS(DGND), .VDD(DVDD), .I(debug_pre));

INVD2BWP7T  I13 ( .ZN(net15), .VSS(DGND), .VDD(DVDD), 
    .I(SAMPLE_INTERNAL));

INVD2BWP7T  I12 ( .ZN(net2), .VSS(DGND), .VDD(DVDD), 
    .I(sample_clk_buff));

INVD2BWP7T  I10 ( .ZN(net22), .VSS(DGND), .VDD(DVDD), 
    .I(QNF_INTERNAL));

dwa_encoder_4b i_shifter[1:0] ( .THERM_OUT({DWA_DATA_THERM[14:0], 
    DWA_ENABLE_THERM[14:0]}), .DATA_IN({dwa_data[3:0], 
    dwa_enable[3:0]}), .DGND(DGND), .DVDD(DVDD), 
    .POINTER(pointer[3:0]));

NR2D4BWP7T  I9 ( .ZN(SAR_INTERNAL), .VSS(DGND), .VDD(DVDD), 
    .A2(sar_done), .A1(sample_digital));

MUX2D2BWP7T  I1 ( .S(EXT_CLK_EN), .I1(EXT_CLK), .I0(net14), 
    .Z(comparator_eval), .VSS(DGND), .VDD(DVDD));

DEL4BWP7T  I5[7:0] ( .Z({comparator_trigger, comparator_delay[6], 
    comparator_delay[5], comparator_delay[4], comparator_delay[3], 
    comparator_delay[2], comparator_delay[1], comparator_delay[0]}), 
    .VDD(DVDD), .VSS(DGND), .I({comparator_delay[6], 
    comparator_delay[5], comparator_delay[4], comparator_delay[3], 
    comparator_delay[2], comparator_delay[1], comparator_delay[0], 
    comparator_trigger_pre}));

BUFFD4BWP7T  I17 ( .Z(sample_clk_buff), .VSS(DGND), .VDD(DVDD), 
    .I(SAMPLE_CLK));

ND2D2BWP7T  I3 ( .A2(comparator_trigger), .ZN(net10), .VSS(DGND), 
    .VDD(DVDD), .A1(nARST));

DFCNQD1BWP7T  i_ctrl_chopper ( .VSS(DGND), .VDD(DVDD), .Q(net7), 
    .D(CHOPPER_INTERNAL), .CP(SAMPLE_INTERNAL), .CDN(nARST));

INR2D2BWP7T  I6 ( .B1(sample_clk_buff), .ZN(comparator_trigger_pre), 
    .VSS(DGND), .VDD(DVDD), .A1(comparator_ready));

OR2D2BWP7T  I2 ( .Z(net14), .A2(sar_done), .A1(net10), .VSS(DGND), 
    .VDD(DVDD));

ND2D4BWP7T  I7 ( .A2(net7), .A1(CHP_EN), .ZN(CHOPPER_INTERNAL), 
    .VSS(DGND), .VDD(DVDD));

ND2D4BWP7T  I15 ( .ZN(net12), .VSS(DGND), .VDD(DVDD), .A2(net22), 
    .A1(sample_clk_buff));

BUFFD2BWP7T  I16 ( .Z(sample_digital), .VSS(DGND), .VDD(DVDD), 
    .I(SAMPLE_INTERNAL));

INVD12BWP7T  I14 ( .ZN(SAMPLE_INTERNAL), .VSS(DGND), .VDD(DVDD), 
    .I(net12));

AN3D4BWP7T  I11 ( .Z(QNF_INTERNAL), .VSS(DGND), .VDD(DVDD), 
    .A3(sar_done), .A2(net15), .A1(net2));

endmodule


// Library - LIB_PEPPER_NSADC, Cell - barrel_shift_4b, View - schematic
// LAST TIME SAVED: Oct 19 15:26:40 2025
// NETLIST TIME: Jan 24 09:35:49 2026

`include "/usr/local/cadence/kits/tsmc/180nm_BCD2/tsmc_libs/libs_r1a_2024/TSMCHOME/digital/Front_End/verilog/tcb018gbwp7t_270a/tcb018gbwp7t_edited.v"

module barrel_shift_4b ( THERM_OUT, DGND, DVDD, POINTER, THERM_IN );


input  DGND, DVDD;

output [14:0]  THERM_OUT;

input [14:0]  THERM_IN;
input [3:0]  POINTER;

interconnect DVDD;
interconnect DGND;
// Buses in the design

interconnect  [14:0]  THERM_IN;

interconnect  [3:0]  POINTER;

interconnect  [14:0]  THERM_OUT;

interconnect  [14:0]  therm_shift1;

interconnect  [14:0]  therm_shift2;

interconnect  [14:0]  therm_shift3;


MUX2D1BWP7T  i_shift_4[14:0] ( .Z(therm_shift1[14:0]), .VDD(DVDD), 
    .VSS(DGND), .I0(THERM_IN[14:0]), .I1({THERM_IN[9], THERM_IN[8], 
    THERM_IN[7], THERM_IN[6], THERM_IN[5], THERM_IN[4], THERM_IN[3], 
    THERM_IN[2], THERM_IN[1], THERM_IN[0], THERM_IN[14], THERM_IN[13], 
    THERM_IN[12], THERM_IN[11], THERM_IN[10]}), .S(POINTER[2]));

MUX2D1BWP7T  i_shift_2[14:0] ( .Z(therm_shift2[14:0]), .VDD(DVDD), 
    .VSS(DGND), .I0(therm_shift1[14:0]), .I1({therm_shift1[12], 
    therm_shift1[11], therm_shift1[10], therm_shift1[9], 
    therm_shift1[8], therm_shift1[7], therm_shift1[6], therm_shift1[5], 
    therm_shift1[4], therm_shift1[3], therm_shift1[2], therm_shift1[1], 
    therm_shift1[0], therm_shift1[14], therm_shift1[13]}), 
    .S(POINTER[1]));

MUX2D1BWP7T  i_shift_1[14:0] ( .Z(THERM_OUT[14:0]), .VDD(DVDD), 
    .VSS(DGND), .I0(therm_shift3[14:0]), .I1({therm_shift3[13], 
    therm_shift3[12], therm_shift3[11], therm_shift3[10], 
    therm_shift3[9], therm_shift3[8], therm_shift3[7], therm_shift3[6], 
    therm_shift3[5], therm_shift3[4], therm_shift3[3], therm_shift3[2], 
    therm_shift3[1], therm_shift3[0], therm_shift3[14]}), 
    .S(POINTER[0]));

MUX2D1BWP7T  i_shift_8[14:0] ( .Z(therm_shift3[14:0]), .VDD(DVDD), 
    .VSS(DGND), .I0(therm_shift2[14:0]), .I1({therm_shift2[7], 
    therm_shift2[6], therm_shift2[5], therm_shift2[4], therm_shift2[3], 
    therm_shift2[2], therm_shift2[1], therm_shift2[0], 
    therm_shift2[14], therm_shift2[13], therm_shift2[12], 
    therm_shift2[11], therm_shift2[10], therm_shift2[9], 
    therm_shift2[8]}), .S(POINTER[3]));

endmodule


// Library - LIB_PEPPER_NSADC, Cell - thermometer_encoder_4b, View -
//schematic
// LAST TIME SAVED: Nov  8 10:25:05 2025
// NETLIST TIME: Jan 24 09:35:47 2026

`include "/usr/local/cadence/kits/tsmc/180nm_BCD2/tsmc_libs/libs_r1a_2024/TSMCHOME/digital/Front_End/verilog/tcb018gbwp7t_270a/tcb018gbwp7t_edited.v"

module thermometer_encoder_4b ( THERM, BINARY, DGND, DVDD, 
    OVERRIDE_HIGH, OVERRIDE_LOW );


input  DGND, DVDD, OVERRIDE_HIGH, OVERRIDE_LOW;

output [15:0]  THERM;

input [3:0]  BINARY;

interconnect OVERRIDE_HIGH;
interconnect DVDD;
interconnect DGND;
interconnect OVERRIDE_LOW;
// Buses in the design

interconnect  [3:0]  BINARY;

interconnect  [15:0]  THERM;

interconnect  [0:1]  net2;

interconnect  [3:0]  therm_select;

interconnect  [0:1]  net1;

interconnect  [3:0]  therm_select_n;


INVD2BWP7T  I9[1:0] ( .ZN(net1[0:1]), .VDD(DVDD), .VSS(DGND), 
    .I(BINARY[1:0]));

INVD2BWP7T  I3[3:0] ( .ZN(therm_select_n[3:0]), .VDD(DVDD), .VSS(DGND), 
    .I(therm_select[3:0]));

INVD2BWP7T  I10[1:0] ( .ZN(net2[0:1]), .VDD(DVDD), .VSS(DGND), 
    .I(net1[0:1]));

thermometer_encoder_2b i_therm_lsb[3:0] ( THERM[15:0], net2[0:1], DGND, 
    DVDD, therm_select[3:0], {therm_select_n[2], therm_select_n[1], 
    therm_select_n[0], OVERRIDE_LOW});

thermometer_encoder_2b i_therm_msb ( .OVERRIDE_LOW(OVERRIDE_LOW), 
    .OVERRIDE_HIGH(OVERRIDE_HIGH), .THERM(therm_select[3:0]), 
    .DGND(DGND), .DVDD(DVDD), .BINARY(BINARY[3:2]));

endmodule


// Library - LIB_PEPPER_NSADC, Cell - nssar_decimator_18b, View -
//schematic
// LAST TIME SAVED: Oct 26 12:26:18 2025
// NETLIST TIME: Jan 24 09:35:51 2026

`include "/usr/local/cadence/kits/tsmc/180nm_BCD2/tsmc_libs/libs_r1a_2024/TSMCHOME/digital/Front_End/verilog/tcb018gbwp7t_270a/tcb018gbwp7t_edited.v"

module nssar_decimator_18b ( CIC_DONE, DECIMATOR_OUT, INT_DEBUG, 
    OVERFLOW, DGND, DVDD, DONE_OVERRIDE, DONE_OVERRIDE_VAL, GAIN, OSR, 
    SAMPLE_CLK, SAR_DATA, nARST );

output  CIC_DONE, INT_DEBUG, OVERFLOW;

inout  DGND, DVDD;

input  DONE_OVERRIDE, DONE_OVERRIDE_VAL, SAMPLE_CLK, nARST;

output [15:0]  DECIMATOR_OUT;

input [3:0]  GAIN;
input [9:0]  SAR_DATA;
input [3:0]  OSR;

interconnect nARST;
interconnect CIC_DONE;
interconnect SAMPLE_CLK;
interconnect tie_high;
interconnect DONE_OVERRIDE;
interconnect count_reset_pre;
interconnect clk_internal;
interconnect DVDD;
interconnect DGND;
interconnect count_reset;
interconnect trigger_a;
interconnect trigger_b;
interconnect clk_internal_n;
interconnect tie_low;
interconnect clk_cic;
interconnect trigger_a_n;
interconnect clear_cic_n;
interconnect by_pass_en;
interconnect DONE_OVERRIDE_VAL;
interconnect INT_DEBUG;
interconnect trigger_b_n;
interconnect cic_pre;
interconnect overflow_int2;
interconnect overflow_pre;
interconnect overflow_dout1;
interconnect OVERFLOW;
interconnect net52;
interconnect net99;
interconnect overflow_dout3;
interconnect completion_flag;
interconnect overflow_dout;
interconnect overflow_dout2;
interconnect net4;
interconnect net12;
interconnect net7;
interconnect net14;
interconnect overflow_dout4;
interconnect net21;
interconnect net16;
// Buses in the design

interconnect  [3:0]  GAIN;

interconnect  [9:0]  SAR_DATA;

interconnect  [3:0]  OSR;

interconnect  [15:0]  DECIMATOR_OUT;

interconnect  [1:0]  gain_n;

interconnect  [17:0]  capture2_n;

interconnect  [4:0]  state_n;

interconnect  [5:0]  state;

interconnect  [15:0]  int1_gated;

interconnect  [18:0]  gain_stage1;

interconnect  [17:0]  dout_pre;

interconnect  [20:0]  int2;

interconnect  [17:0]  carry_dout;

interconnect  [17:0]  capture1;

interconnect  [18:0]  gain_stage2;

interconnect  [17:0]  capture2;

interconnect  [20:0]  sum2;

interconnect  [20:0]  carry2;

interconnect  [15:0]  sum1;

interconnect  [20:0]  int2_gated;

interconnect  [5:0]  state_pre;

interconnect  [3:0]  state_carry;

interconnect  [15:0]  int1;

interconnect  [16:0]  gain_stage3;

interconnect  [15:0]  carry1;

interconnect  [4:0]  state_dec_n;

interconnect  [4:0]  state_dec;


DFCNQD1BWP7T  I55 ( .VSS(DGND), .VDD(DVDD), .Q(OVERFLOW), 
    .D(overflow_pre), .CP(clk_internal), .CDN(nARST));

DFCNQD1BWP7T  I24[17:0] ( .Q(capture1[17:0]), .VDD(DVDD), .VSS(DGND), 
    .CDN(nARST), .CP(trigger_b), .D(gain_stage2[18:1]));

DFCNQD1BWP7T  I33[20:0] ( .Q(int2[20:0]), .VDD(DVDD), .VSS(DGND), 
    .CDN(nARST), .CP(clk_cic), .D(sum2[20:0]));

DFCNQD1BWP7T  I19[17:0] ( .Q(capture2[17:0]), .VDD(DVDD), .VSS(DGND), 
    .CDN(nARST), .CP(trigger_a), .D(gain_stage2[17:0]));

DFCNQD1BWP7T  I40[15:0] ( .Q(int1[15:0]), .VDD(DVDD), .VSS(DGND), 
    .CDN(nARST), .CP(clk_cic), .D(sum1[15:0]));

DFCNQD1BWP7T  i_state_lsb[4:0] ( .Q(state[4:0]), .VDD(DVDD), 
    .VSS(DGND), .CDN(nARST), .CP(clk_internal), .D(state_pre[4:0]));

BUFFD4BWP7T  I13 ( .Z(count_reset), .VSS(DGND), .VDD(DVDD), 
    .I(count_reset_pre));

HA1D1BWP7T  I6[4:0] ( .CO({count_reset_pre, state_carry[3], 
    state_carry[2], state_carry[1], state_carry[0]}), 
    .S(state_dec_n[4:0]), .VDD(DVDD), .VSS(DGND), .A(state_n[4:0]), 
    .B({state_carry[3], state_carry[2], state_carry[1], state_carry[0], 
    tie_high}));

MUX2D1BWP7T  I35[18:0] ( .Z(gain_stage1[18:0]), .VDD(DVDD), .VSS(DGND), 
    .I0(int2[20:2]), .I1(int2[18:0]), .S(GAIN[3]));

MUX2D1BWP7T  I27[16:0] ( .Z(gain_stage3[16:0]), .VDD(DVDD), .VSS(DGND), 
    .I0(dout_pre[17:1]), .I1({dout_pre[15], dout_pre[14], dout_pre[13], 
    dout_pre[12], dout_pre[11], dout_pre[10], dout_pre[9], dout_pre[8], 
    dout_pre[7], dout_pre[6], dout_pre[5], dout_pre[4], dout_pre[3], 
    dout_pre[2], dout_pre[1], dout_pre[0], tie_low}), .S(GAIN[1]));

MUX2D1BWP7T  I3 ( .S(DONE_OVERRIDE), .I1(DONE_OVERRIDE_VAL), 
    .I0(trigger_b), .Z(cic_pre), .VSS(DGND), .VDD(DVDD));

MUX2D1BWP7T  I32[18:0] ( .Z(gain_stage2[18:0]), .VDD(DVDD), .VSS(DGND), 
    .I0(gain_stage1[18:0]), .I1({gain_stage1[16], gain_stage1[15], 
    gain_stage1[14], gain_stage1[13], gain_stage1[12], gain_stage1[11], 
    gain_stage1[10], gain_stage1[9], gain_stage1[8], gain_stage1[7], 
    gain_stage1[6], gain_stage1[5], gain_stage1[4], gain_stage1[3], 
    gain_stage1[2], gain_stage1[1], gain_stage1[0], tie_low, tie_low}), 
    .S(GAIN[2]));

MUX2D1BWP7T  I22[15:0] ( .Z(DECIMATOR_OUT[15:0]), .VDD(DVDD), 
    .VSS(DGND), .I0(gain_stage3[16:1]), .I1(gain_stage3[15:0]), 
    .S(GAIN[0]));

MUX2D1BWP7T  I14[4:0] ( .Z(state_pre[4:0]), .VDD(DVDD), .VSS(DGND), 
    .I0(state_dec[4:0]), .I1({OSR[3], OSR[2], OSR[1], OSR[0], 
    tie_low}), .S(count_reset));

TIEHBWP7T  I39 ( .Z(tie_high), .VSS(DGND), .VDD(DVDD));

DEL4BWP7T  I20 ( .Z(net99), .VSS(DGND), .VDD(DVDD), .I(clk_internal));

INVD1BWP7T  I21[17:0] ( .ZN(capture2_n[17:0]), .VDD(DVDD), .VSS(DGND), 
    .I(capture2[17:0]));

INVD1BWP7T  I8[4:0] ( .ZN(state_n[4:0]), .VDD(DVDD), .VSS(DGND), 
    .I(state[4:0]));

INVD1BWP7T  I7[4:0] ( .ZN(state_dec[4:0]), .VDD(DVDD), .VSS(DGND), 
    .I(state_dec_n[4:0]));

XOR2D1BWP7T  I1 ( .Z(state_pre[5]), .A2(count_reset), .A1(state[5]), 
    .VSS(DGND), .VDD(DVDD));

OR2D1BWP7T  I64 ( .A2(carry2[20]), .Z(overflow_int2), .A1(net12), 
    .VSS(DGND), .VDD(DVDD));

OR2D1BWP7T  I2 ( .Z(state[5]), .A2(net52), .A1(by_pass_en), .VSS(DGND), 
    .VDD(DVDD));

OR2D1BWP7T  I75 ( .A2(GAIN[2]), .A1(GAIN[3]), .VSS(DGND), .Z(net7), 
    .VDD(DVDD));

INVD4BWP7T  I73[1:0] ( .ZN(gain_n[1:0]), .VDD(DVDD), .VSS(DGND), 
    .I(GAIN[1:0]));

INVD4BWP7T  I23 ( .ZN(clk_internal), .VSS(DGND), .VDD(DVDD), 
    .I(clk_internal_n));

INVD4BWP7T  I26 ( .ZN(clk_internal_n), .I(SAMPLE_CLK), .VSS(DGND), 
    .VDD(DVDD));

TIELBWP7T  I36 ( .ZN(tie_low), .VSS(DGND), .VDD(DVDD));

FA1D1BWP7T  I25[17:0] ( .CO(carry_dout[17:0]), .S(dout_pre[17:0]), 
    .VDD(DVDD), .VSS(DGND), .A(capture1[17:0]), .B(capture2_n[17:0]), 
    .CI({carry_dout[16], carry_dout[15], carry_dout[14], 
    carry_dout[13], carry_dout[12], carry_dout[11], carry_dout[10], 
    carry_dout[9], carry_dout[8], carry_dout[7], carry_dout[6], 
    carry_dout[5], carry_dout[4], carry_dout[3], carry_dout[2], 
    carry_dout[1], carry_dout[0], tie_high}));

FA1D1BWP7T  I31[20:0] ( .CO(carry2[20:0]), .S(sum2[20:0]), .VDD(DVDD), 
    .VSS(DGND), .A(int2_gated[20:0]), .B({tie_low, tie_low, tie_low, 
    tie_low, tie_low, sum1[15], sum1[14], sum1[13], sum1[12], sum1[11], 
    sum1[10], sum1[9], sum1[8], sum1[7], sum1[6], sum1[5], sum1[4], 
    sum1[3], sum1[2], sum1[1], sum1[0]}), .CI({carry2[19], carry2[18], 
    carry2[17], carry2[16], carry2[15], carry2[14], carry2[13], 
    carry2[12], carry2[11], carry2[10], carry2[9], carry2[8], 
    carry2[7], carry2[6], carry2[5], carry2[4], carry2[3], carry2[2], 
    carry2[1], carry2[0], tie_low}));

FA1D1BWP7T  I38[15:0] ( .CO(carry1[15:0]), .S(sum1[15:0]), .VDD(DVDD), 
    .VSS(DGND), .A(int1_gated[15:0]), .B({tie_low, tie_low, tie_low, 
    tie_low, tie_low, tie_low, SAR_DATA[9], SAR_DATA[8], SAR_DATA[7], 
    SAR_DATA[6], SAR_DATA[5], SAR_DATA[4], SAR_DATA[3], SAR_DATA[2], 
    SAR_DATA[1], SAR_DATA[0]}), .CI({carry1[14], carry1[13], 
    carry1[12], carry1[11], carry1[10], carry1[9], carry1[8], 
    carry1[7], carry1[6], carry1[5], carry1[4], carry1[3], carry1[2], 
    carry1[1], carry1[0], tie_low}));

BUFFD12BWP7T  I18 ( .Z(clk_cic), .VSS(DGND), .VDD(DVDD), .I(net99));

INVD8BWP7T  I5 ( .ZN(clear_cic_n), .I(CIC_DONE), .VSS(DGND), 
    .VDD(DVDD));

INVD8BWP7T  I9 ( .ZN(trigger_a), .VSS(DGND), .VDD(DVDD), 
    .I(trigger_a_n));

INVD8BWP7T  I11 ( .ZN(trigger_b), .VSS(DGND), .VDD(DVDD), 
    .I(trigger_b_n));

AN2D1BWP7T  I61 ( .Z(completion_flag), .A2(count_reset), .A1(state[5]), 
    .VDD(DVDD), .VSS(DGND));

AN2D1BWP7T  I37[15:0] ( .Z(int1_gated[15:0]), .VDD(DVDD), .VSS(DGND), 
    .A1(int1[15:0]), .A2(clear_cic_n));

AN2D1BWP7T  I29[20:0] ( .Z(int2_gated[20:0]), .VDD(DVDD), .VSS(DGND), 
    .A1(int2[20:0]), .A2(clear_cic_n));

ND2D2BWP7T  I60 ( .A2(clk_internal_n), .A1(completion_flag), 
    .VDD(DVDD), .VSS(DGND), .ZN(trigger_b_n));

ND2D2BWP7T  I10 ( .A2(clk_internal_n), .ZN(trigger_a_n), .VSS(DGND), 
    .VDD(DVDD), .A1(net4));

INR2D1BWP7T  I62 ( .ZN(net4), .B1(state[5]), .A1(count_reset), 
    .VDD(DVDD), .VSS(DGND));

INR2D1BWP7T  I57 ( .B1(overflow_dout1), .A1(completion_flag), 
    .ZN(overflow_dout), .VSS(DGND), .VDD(DVDD));

NR4D1BWP7T  I30 ( .A4(OSR[0]), .A3(OSR[1]), .A2(OSR[2]), .A1(OSR[3]), 
    .ZN(by_pass_en), .VSS(DGND), .VDD(DVDD));

INVD2BWP7T  I15 ( .ZN(INT_DEBUG), .VSS(DGND), .VDD(DVDD), 
    .I(carry1[9]));

DFSNQD1BWP7T  i_state_msb ( .VSS(DGND), .VDD(DVDD), .Q(net52), 
    .SDN(nARST), .D(state_pre[5]), .CP(clk_internal));

DFCNQD2BWP7T  I4 ( .VSS(DGND), .VDD(DVDD), .Q(CIC_DONE), .D(cic_pre), 
    .CP(clk_internal), .CDN(nARST));

OR3D1BWP7T  I56 ( .A3(overflow_dout), .Z(overflow_pre), .VSS(DGND), 
    .VDD(DVDD), .A2(OVERFLOW), .A1(overflow_int2));

NR2D1BWP7T  I74 ( .A2(gain_n[0]), .A1(carry_dout[16]), .VDD(DVDD), 
    .ZN(overflow_dout2), .VSS(DGND));

NR2D1BWP7T  I70 ( .ZN(overflow_dout3), .A2(gain_n[1]), 
    .A1(carry_dout[15]), .VDD(DVDD), .VSS(DGND));

AN2D0BWP7T  I71 ( .A2(net21), .A1(carry_dout[17]), .Z(overflow_dout1), 
    .VDD(DVDD), .VSS(DGND));

ND2D0BWP7T  I67 ( .A2(net7), .A1(carry2[18]), .VDD(DVDD), .VSS(DGND), 
    .ZN(net14));

ND2D0BWP7T  I65 ( .ZN(net12), .A2(net14), .A1(net16), .VSS(DGND), 
    .VDD(DVDD));

ND3D1BWP7T  I66 ( .A3(GAIN[3]), .ZN(net16), .A2(GAIN[2]), 
    .A1(carry2[16]), .VSS(DGND), .VDD(DVDD));

NR3D1BWP7T  I68 ( .ZN(overflow_dout4), .A3(gain_n[1]), .A2(gain_n[0]), 
    .A1(carry_dout[14]), .VDD(DVDD), .VSS(DGND));

NR3D1BWP7T  I69 ( .ZN(net21), .A3(overflow_dout2), .A2(overflow_dout3), 
    .A1(overflow_dout4), .VDD(DVDD), .VSS(DGND));

endmodule


// Library - LIB_PEPPER_NSADC, Cell - dwa_encoder_4b, View - schematic
// LAST TIME SAVED: Oct 26 09:58:41 2025
// NETLIST TIME: Jan 24 09:35:50 2026

`include "/usr/local/cadence/kits/tsmc/180nm_BCD2/tsmc_libs/libs_r1a_2024/TSMCHOME/digital/Front_End/verilog/tcb018gbwp7t_270a/tcb018gbwp7t_edited.v"

module dwa_encoder_4b ( THERM_OUT, DATA_IN, DGND, DVDD, POINTER );


input  DGND, DVDD;

output [14:0]  THERM_OUT;

input [3:0]  DATA_IN;
input [3:0]  POINTER;

interconnect DVDD;
interconnect DGND;
// Buses in the design

interconnect  [3:0]  DATA_IN;

interconnect  [3:0]  POINTER;

interconnect  [14:0]  THERM_OUT;

interconnect  [15:0]  data_therm_pre;


thermometer_encoder_4b i_encoder ( .OVERRIDE_LOW(DGND), .DGND(DGND), 
    .DVDD(DVDD), .OVERRIDE_HIGH(DGND), .THERM(data_therm_pre[15:0]), 
    .BINARY(DATA_IN[3:0]));

barrel_shift_4b i_shifter ( .THERM_IN(data_therm_pre[14:0]), 
    .DGND(DGND), .DVDD(DVDD), .POINTER(POINTER[3:0]), 
    .THERM_OUT(THERM_OUT[14:0]));

endmodule


